"""Calibrated reward scalars η_R and η_p (generated by calibrate_eta.py).

The selection/reward heuristic is  R = α₁·Δλ₂/n + α₂·η_R·ΔR_G/n² + α₃·η_p·Δp_min
with ΔR_G the positive reduction R_G^old - R_G^new and Δp_min the positive change
in the minimum resistance curvature.  η_R and η_p scale the second and third terms
so that all three have comparable magnitude on average over the construction regime.

Values are interpolated by graph size n at runtime; reward_eta/reward_eta_p config
overrides take precedence when set > 0.
"""

ETA_NS = [ 8., 12., 16., 24., 32., 48., 64.]
ETA_R_VALS = [7.95959908e-01, 3.65065864e-01, 9.76347650e-02, 1.97815166e-02,
       6.19660107e-03, 1.43558275e-03, 4.57831964e-04]
ETA_P_VALS = [0.61502924, 0.3047325 , 0.09205806, 0.03386759, 0.01294088,
       0.00474757, 0.00226865]

