"""Calibrate the reward scaling constants η_R and η_p for the analytic algorithm.

The selection / reward heuristic (algorithm.md, Preliminaries) is:

    R = α₁·Δλ₂/n + α₂·η_R·ΔR_G/n² + α₃·η_p·Δp_min

where ΔR_G is the positive reduction R_G^old - R_G^new and Δp_min is the
positive change in the minimum resistance curvature.  The scalars η_R and η_p
are "supplied by the caller"; this script estimates them so that the three
terms have comparable magnitude on average over the construction regime:

    η_R = mean(|Δλ₂/n|) / mean(|ΔR_G/n²|)
    η_p = mean(|Δλ₂/n|) / mean(|Δp_min|)

Run from the project root:

    python -m analytic_tractable_test_deepseek.calibrate_eta

The results are written to ``analytic_tractable_test_deepseek/calibration.py``,
which the environment reads at runtime.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

# Ensure the project root is on the path.
_project_root = str(Path(__file__).resolve().parent.parent)
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

from analytic_tractable_test_deepseek.graph_math import (
    build_path_adjacency,
    spectral_features,
)
from analytic_tractable_test_deepseek.analytic_state import p_min_for_adj


def _random_non_edge(adj: np.ndarray, rng: np.random.RandomState) -> tuple[int, int]:
    mask = np.triu(adj == 0, k=1)
    rows, cols = np.where(mask)
    if rows.size == 0:
        raise RuntimeError("No non-edges available - graph is complete")
    idx = int(rng.randint(rows.size))
    return int(rows[idx]), int(cols[idx])


def calibrate(
    ns: list[int],
    total_samples: int,
    traj_len: int = 50,
    seed: int = 42,
) -> dict[int, dict[str, float]]:
    """Estimate η_R and η_p per graph size over random edge-add trajectories."""
    rng = np.random.RandomState(seed)
    out: dict[int, dict[str, float]] = {}

    print("=" * 76)
    print("  η_R / η_p calibration  (reward-term magnitude matching)")
    print("=" * 76)
    print(f"  Samples per n: {total_samples}    Trajectory length: {traj_len}    Seed: {seed}")
    print()
    header = (
        f"{'n':>6}  {'mean|Δλ₂/n|':>14}  {'mean|ΔR_G/n²|':>16}  "
        f"{'mean|Δp_min|':>14}  {'η_R':>12}  {'η_p':>12}"
    )
    print(header)
    print("-" * len(header))

    for n in ns:
        deltas_l2: list[float] = []
        deltas_rg: list[float] = []
        deltas_pmin: list[float] = []
        collected = 0

        while collected < total_samples:
            adj = build_path_adjacency(n).astype(np.uint8)
            for _ in range(traj_len):
                try:
                    i, j = _random_non_edge(adj, rng)
                except RuntimeError:
                    break

                l2_old, *_rest, rg_old, _mult, _ev = spectral_features(adj)
                pmin_old = p_min_for_adj(adj)

                adj[i, j] = 1
                adj[j, i] = 1

                l2_new, *_rest, rg_new, _mult, _ev = spectral_features(adj)
                pmin_new = p_min_for_adj(adj)

                deltas_l2.append(float(l2_new - l2_old) / float(max(1, n)))
                deltas_rg.append(float(rg_old - rg_new) / float(max(1, n * n)))
                deltas_pmin.append(float(pmin_new - pmin_old))
                collected += 1
                if collected >= total_samples:
                    break

        arr_l2 = np.asarray(deltas_l2[:total_samples], dtype=np.float64)
        arr_rg = np.asarray(deltas_rg[:total_samples], dtype=np.float64)
        arr_pm = np.asarray(deltas_pmin[:total_samples], dtype=np.float64)

        mean_l2 = float(np.mean(np.abs(arr_l2)))
        mean_rg = float(np.mean(np.abs(arr_rg)))
        mean_pm = float(np.mean(np.abs(arr_pm)))

        eta_r = mean_l2 / mean_rg if mean_rg > 1e-15 else 1.0
        eta_p = mean_l2 / mean_pm if mean_pm > 1e-15 else 1.0

        out[int(n)] = {
            "eta_R": float(eta_r),
            "eta_p": float(eta_p),
            "mean_abs_dl2_over_n": float(mean_l2),
            "mean_abs_drg_over_n2": float(mean_rg),
            "mean_abs_dpmin": float(mean_pm),
        }
        print(
            f"{n:>6}  {mean_l2:>14.6e}  {mean_rg:>16.6e}  "
            f"{mean_pm:>14.6e}  {eta_r:>12.6f}  {eta_p:>12.6f}"
        )

    print("-" * len(header))
    return out


def write_calibration_file(results: dict[int, dict[str, float]], path: Path) -> None:
    """Write the per-size tables to ``calibration.py`` for runtime use."""
    ns = sorted(results.keys())
    eta_r_vals = [results[n]["eta_R"] for n in ns]
    eta_p_vals = [results[n]["eta_p"] for n in ns]

    lines = [
        '"""Calibrated reward scalars η_R and η_p (generated by calibrate_eta.py).',
        "",
        "The selection/reward heuristic is  R = α₁·Δλ₂/n + α₂·η_R·ΔR_G/n² + α₃·η_p·Δp_min",
        "with ΔR_G the positive reduction R_G^old - R_G^new and Δp_min the positive change",
        "in the minimum resistance curvature.  η_R and η_p scale the second and third terms",
        "so that all three have comparable magnitude on average over the construction regime.",
        "",
        "Values are interpolated by graph size n at runtime; reward_eta/reward_eta_p config",
        "overrides take precedence when set > 0.",
        '"""',
        "",
        "ETA_NS = " + repr(np.asarray(ns, dtype=np.float64)).replace("array(", "").rstrip(")"),
        "ETA_R_VALS = " + repr(np.asarray(eta_r_vals, dtype=np.float64)).replace("array(", "").rstrip(")"),
        "ETA_P_VALS = " + repr(np.asarray(eta_p_vals, dtype=np.float64)).replace("array(", "").rstrip(")"),
        "",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\n[calibrate_eta] wrote {path}")


def main() -> None:
    results = calibrate(
        ns=[8, 12, 16, 24, 32, 48, 64],
        total_samples=400,
        traj_len=50,
        seed=42,
    )
    out_path = Path(__file__).resolve().parent / "calibration.py"
    write_calibration_file(results, out_path)


if __name__ == "__main__":
    main()
